# Use the official .NET 8 runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS build
WORKDIR /app

EXPOSE 5203
# EXPOSE 5003

# Copy the rest of the source code
COPY . .


WORKDIR /app/LoanEligibilityAPI


ENTRYPOINT ["dotnet", "watch", "run"]